/* This file was generated by SableCC (http://www.sablecc.org/). */

package com.dat405.nldl.node;

import com.dat405.nldl.analysis.*;

@SuppressWarnings("nls")
public final class AAssGroupBlock extends PGroupBlock
{
    private PVar _var_;
    private PConnectionDcl _connectionDcl_;

    public AAssGroupBlock()
    {
        // Constructor
    }

    public AAssGroupBlock(
        @SuppressWarnings("hiding") PVar _var_,
        @SuppressWarnings("hiding") PConnectionDcl _connectionDcl_)
    {
        // Constructor
        setVar(_var_);

        setConnectionDcl(_connectionDcl_);

    }

    @Override
    public Object clone()
    {
        return new AAssGroupBlock(
            cloneNode(this._var_),
            cloneNode(this._connectionDcl_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAAssGroupBlock(this);
    }

    public PVar getVar()
    {
        return this._var_;
    }

    public void setVar(PVar node)
    {
        if(this._var_ != null)
        {
            this._var_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._var_ = node;
    }

    public PConnectionDcl getConnectionDcl()
    {
        return this._connectionDcl_;
    }

    public void setConnectionDcl(PConnectionDcl node)
    {
        if(this._connectionDcl_ != null)
        {
            this._connectionDcl_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._connectionDcl_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._var_)
            + toString(this._connectionDcl_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._var_ == child)
        {
            this._var_ = null;
            return;
        }

        if(this._connectionDcl_ == child)
        {
            this._connectionDcl_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._var_ == oldChild)
        {
            setVar((PVar) newChild);
            return;
        }

        if(this._connectionDcl_ == oldChild)
        {
            setConnectionDcl((PConnectionDcl) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
