/* This file was generated by SableCC (http://www.sablecc.org/). */

package com.dat405.nldl.node;

import com.dat405.nldl.analysis.*;

@SuppressWarnings("nls")
public final class AConnectionGroupBlock extends PGroupBlock
{
    private PConnectionDcl _connectionDcl_;

    public AConnectionGroupBlock()
    {
        // Constructor
    }

    public AConnectionGroupBlock(
        @SuppressWarnings("hiding") PConnectionDcl _connectionDcl_)
    {
        // Constructor
        setConnectionDcl(_connectionDcl_);

    }

    @Override
    public Object clone()
    {
        return new AConnectionGroupBlock(
            cloneNode(this._connectionDcl_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAConnectionGroupBlock(this);
    }

    public PConnectionDcl getConnectionDcl()
    {
        return this._connectionDcl_;
    }

    public void setConnectionDcl(PConnectionDcl node)
    {
        if(this._connectionDcl_ != null)
        {
            this._connectionDcl_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._connectionDcl_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._connectionDcl_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._connectionDcl_ == child)
        {
            this._connectionDcl_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._connectionDcl_ == oldChild)
        {
            setConnectionDcl((PConnectionDcl) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
