/* This file was generated by SableCC (http://www.sablecc.org/). */

package com.dat405.nldl.node;

import com.dat405.nldl.analysis.*;

@SuppressWarnings("nls")
public final class AGroupGroupBlock extends PGroupBlock
{
    private PGroupDcl _groupDcl_;

    public AGroupGroupBlock()
    {
        // Constructor
    }

    public AGroupGroupBlock(
        @SuppressWarnings("hiding") PGroupDcl _groupDcl_)
    {
        // Constructor
        setGroupDcl(_groupDcl_);

    }

    @Override
    public Object clone()
    {
        return new AGroupGroupBlock(
            cloneNode(this._groupDcl_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAGroupGroupBlock(this);
    }

    public PGroupDcl getGroupDcl()
    {
        return this._groupDcl_;
    }

    public void setGroupDcl(PGroupDcl node)
    {
        if(this._groupDcl_ != null)
        {
            this._groupDcl_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._groupDcl_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._groupDcl_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._groupDcl_ == child)
        {
            this._groupDcl_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._groupDcl_ == oldChild)
        {
            setGroupDcl((PGroupDcl) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
