/* This file was generated by SableCC (http://www.sablecc.org/). */

package com.dat405.nldl.node;

import java.util.*;
import com.dat405.nldl.analysis.*;

@SuppressWarnings("nls")
public final class AMultiConnectionDcl extends PConnectionDcl
{
    private final LinkedList<PConnector> _connector_ = new LinkedList<PConnector>();

    public AMultiConnectionDcl()
    {
        // Constructor
    }

    public AMultiConnectionDcl(
        @SuppressWarnings("hiding") List<?> _connector_)
    {
        // Constructor
        setConnector(_connector_);

    }

    @Override
    public Object clone()
    {
        return new AMultiConnectionDcl(
            cloneList(this._connector_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAMultiConnectionDcl(this);
    }

    public LinkedList<PConnector> getConnector()
    {
        return this._connector_;
    }

    public void setConnector(List<?> list)
    {
        for(PConnector e : this._connector_)
        {
            e.parent(null);
        }
        this._connector_.clear();

        for(Object obj_e : list)
        {
            PConnector e = (PConnector) obj_e;
            if(e.parent() != null)
            {
                e.parent().removeChild(e);
            }

            e.parent(this);
            this._connector_.add(e);
        }
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._connector_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._connector_.remove(child))
        {
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        for(ListIterator<PConnector> i = this._connector_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set((PConnector) newChild);
                    newChild.parent(this);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

        throw new RuntimeException("Not a child.");
    }
}
