/* This file was generated by SableCC (http://www.sablecc.org/). */

package com.dat405.nldl.node;

import com.dat405.nldl.analysis.*;

@SuppressWarnings("nls")
public final class ANumV extends PV
{
    private TConst _const_;

    public ANumV()
    {
        // Constructor
    }

    public ANumV(
        @SuppressWarnings("hiding") TConst _const_)
    {
        // Constructor
        setConst(_const_);

    }

    @Override
    public Object clone()
    {
        return new ANumV(
            cloneNode(this._const_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseANumV(this);
    }

    public TConst getConst()
    {
        return this._const_;
    }

    public void setConst(TConst node)
    {
        if(this._const_ != null)
        {
            this._const_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._const_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._const_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._const_ == child)
        {
            this._const_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._const_ == oldChild)
        {
            setConst((TConst) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
