/* This file was generated by SableCC (http://www.sablecc.org/). */

package com.dat405.nldl.node;

import com.dat405.nldl.analysis.*;

@SuppressWarnings("nls")
public final class ARrConnectionDcl extends PConnectionDcl
{
    private PConnector _first_;
    private PConnector _second_;

    public ARrConnectionDcl()
    {
        // Constructor
    }

    public ARrConnectionDcl(
        @SuppressWarnings("hiding") PConnector _first_,
        @SuppressWarnings("hiding") PConnector _second_)
    {
        // Constructor
        setFirst(_first_);

        setSecond(_second_);

    }

    @Override
    public Object clone()
    {
        return new ARrConnectionDcl(
            cloneNode(this._first_),
            cloneNode(this._second_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseARrConnectionDcl(this);
    }

    public PConnector getFirst()
    {
        return this._first_;
    }

    public void setFirst(PConnector node)
    {
        if(this._first_ != null)
        {
            this._first_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._first_ = node;
    }

    public PConnector getSecond()
    {
        return this._second_;
    }

    public void setSecond(PConnector node)
    {
        if(this._second_ != null)
        {
            this._second_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._second_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._first_)
            + toString(this._second_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._first_ == child)
        {
            this._first_ = null;
            return;
        }

        if(this._second_ == child)
        {
            this._second_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._first_ == oldChild)
        {
            setFirst((PConnector) newChild);
            return;
        }

        if(this._second_ == oldChild)
        {
            setSecond((PConnector) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
