/* This file was generated by SableCC (http://www.sablecc.org/). */

package com.dat405.nldl.node;

import com.dat405.nldl.analysis.*;

@SuppressWarnings("nls")
public final class ASettingGroupBlock extends PGroupBlock
{
    private PSettingBlock _settingBlock_;

    public ASettingGroupBlock()
    {
        // Constructor
    }

    public ASettingGroupBlock(
        @SuppressWarnings("hiding") PSettingBlock _settingBlock_)
    {
        // Constructor
        setSettingBlock(_settingBlock_);

    }

    @Override
    public Object clone()
    {
        return new ASettingGroupBlock(
            cloneNode(this._settingBlock_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseASettingGroupBlock(this);
    }

    public PSettingBlock getSettingBlock()
    {
        return this._settingBlock_;
    }

    public void setSettingBlock(PSettingBlock node)
    {
        if(this._settingBlock_ != null)
        {
            this._settingBlock_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._settingBlock_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._settingBlock_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._settingBlock_ == child)
        {
            this._settingBlock_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._settingBlock_ == oldChild)
        {
            setSettingBlock((PSettingBlock) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
