/* This file was generated by SableCC (http://www.sablecc.org/). */

package com.dat405.nldl.node;

import java.util.*;
import com.dat405.nldl.analysis.*;

@SuppressWarnings("nls")
public final class ASettingDcl extends PSettingDcl
{
    private PVar _var_;
    private final LinkedList<PSettingBlock> _settingBlock_ = new LinkedList<PSettingBlock>();

    public ASettingDcl()
    {
        // Constructor
    }

    public ASettingDcl(
        @SuppressWarnings("hiding") PVar _var_,
        @SuppressWarnings("hiding") List<?> _settingBlock_)
    {
        // Constructor
        setVar(_var_);

        setSettingBlock(_settingBlock_);

    }

    @Override
    public Object clone()
    {
        return new ASettingDcl(
            cloneNode(this._var_),
            cloneList(this._settingBlock_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseASettingDcl(this);
    }

    public PVar getVar()
    {
        return this._var_;
    }

    public void setVar(PVar node)
    {
        if(this._var_ != null)
        {
            this._var_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._var_ = node;
    }

    public LinkedList<PSettingBlock> getSettingBlock()
    {
        return this._settingBlock_;
    }

    public void setSettingBlock(List<?> list)
    {
        for(PSettingBlock e : this._settingBlock_)
        {
            e.parent(null);
        }
        this._settingBlock_.clear();

        for(Object obj_e : list)
        {
            PSettingBlock e = (PSettingBlock) obj_e;
            if(e.parent() != null)
            {
                e.parent().removeChild(e);
            }

            e.parent(this);
            this._settingBlock_.add(e);
        }
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._var_)
            + toString(this._settingBlock_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._var_ == child)
        {
            this._var_ = null;
            return;
        }

        if(this._settingBlock_.remove(child))
        {
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._var_ == oldChild)
        {
            setVar((PVar) newChild);
            return;
        }

        for(ListIterator<PSettingBlock> i = this._settingBlock_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set((PSettingBlock) newChild);
                    newChild.parent(this);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

        throw new RuntimeException("Not a child.");
    }
}
