/* This file was generated by SableCC (http://www.sablecc.org/). */

package com.dat405.nldl.parser;

import com.dat405.nldl.node.*;
import com.dat405.nldl.analysis.*;

class TokenIndex extends AnalysisAdapter
{
    int index;

    @Override
    public void caseTRouter(@SuppressWarnings("unused") TRouter node)
    {
        this.index = 0;
    }

    @Override
    public void caseTGroup(@SuppressWarnings("unused") TGroup node)
    {
        this.index = 1;
    }

    @Override
    public void caseTSegment(@SuppressWarnings("unused") TSegment node)
    {
        this.index = 2;
    }

    @Override
    public void caseTSettings(@SuppressWarnings("unused") TSettings node)
    {
        this.index = 3;
    }

    @Override
    public void caseTSetting(@SuppressWarnings("unused") TSetting node)
    {
        this.index = 4;
    }

    @Override
    public void caseTConnection(@SuppressWarnings("unused") TConnection node)
    {
        this.index = 5;
    }

    @Override
    public void caseTIpKeyword(@SuppressWarnings("unused") TIpKeyword node)
    {
        this.index = 6;
    }

    @Override
    public void caseTMain(@SuppressWarnings("unused") TMain node)
    {
        this.index = 7;
    }

    @Override
    public void caseTDot(@SuppressWarnings("unused") TDot node)
    {
        this.index = 8;
    }

    @Override
    public void caseTInterfaceType(@SuppressWarnings("unused") TInterfaceType node)
    {
        this.index = 9;
    }

    @Override
    public void caseTProtocol(@SuppressWarnings("unused") TProtocol node)
    {
        this.index = 10;
    }

    @Override
    public void caseTConst(@SuppressWarnings("unused") TConst node)
    {
        this.index = 11;
    }

    @Override
    public void caseTEqual(@SuppressWarnings("unused") TEqual node)
    {
        this.index = 12;
    }

    @Override
    public void caseTLParenthesis(@SuppressWarnings("unused") TLParenthesis node)
    {
        this.index = 13;
    }

    @Override
    public void caseTRParenthesis(@SuppressWarnings("unused") TRParenthesis node)
    {
        this.index = 14;
    }

    @Override
    public void caseTLBrace(@SuppressWarnings("unused") TLBrace node)
    {
        this.index = 15;
    }

    @Override
    public void caseTRBrace(@SuppressWarnings("unused") TRBrace node)
    {
        this.index = 16;
    }

    @Override
    public void caseTLBracket(@SuppressWarnings("unused") TLBracket node)
    {
        this.index = 17;
    }

    @Override
    public void caseTRBracket(@SuppressWarnings("unused") TRBracket node)
    {
        this.index = 18;
    }

    @Override
    public void caseTArrow(@SuppressWarnings("unused") TArrow node)
    {
        this.index = 19;
    }

    @Override
    public void caseTSlash(@SuppressWarnings("unused") TSlash node)
    {
        this.index = 20;
    }

    @Override
    public void caseTSemi(@SuppressWarnings("unused") TSemi node)
    {
        this.index = 21;
    }

    @Override
    public void caseTComma(@SuppressWarnings("unused") TComma node)
    {
        this.index = 22;
    }

    @Override
    public void caseTString(@SuppressWarnings("unused") TString node)
    {
        this.index = 23;
    }

    @Override
    public void caseTIdentifier(@SuppressWarnings("unused") TIdentifier node)
    {
        this.index = 24;
    }

    @Override
    public void caseEOF(@SuppressWarnings("unused") EOF node)
    {
        this.index = 25;
    }
}
