/* This file was generated by SableCC (http://www.sablecc.org/). */

package com.dat405.nldl.lexer;

import java.io.*;
import com.dat405.nldl.node.*;

@SuppressWarnings("nls")
public class Lexer
{
    protected Token token;
    protected State state = State.INITIAL;

    private IPushbackReader in;
    private int line;
    private int pos;
    private boolean cr;
    private boolean eof;
    private final StringBuffer text = new StringBuffer();

    @SuppressWarnings("unused")
    protected void filter() throws LexerException, IOException
    {
        // Do nothing
    }

    public Lexer(@SuppressWarnings("hiding") final PushbackReader in)
    {
        this.in = new IPushbackReader() {

            private PushbackReader pushbackReader = in;
            
            @Override
            public void unread(int c) throws IOException {
                pushbackReader.unread(c);
            }
            
            @Override
            public int read() throws IOException {
                return pushbackReader.read();
            }
        };
    }
 
    public Lexer(@SuppressWarnings("hiding") IPushbackReader in)
    {
        this.in = in;
    }
 
    public Token peek() throws LexerException, IOException
    {
        while(this.token == null)
        {
            this.token = getToken();
            filter();
        }

        return this.token;
    }

    public Token next() throws LexerException, IOException
    {
        while(this.token == null)
        {
            this.token = getToken();
            filter();
        }

        Token result = this.token;
        this.token = null;
        return result;
    }

    protected Token getToken() throws IOException, LexerException
    {
        int dfa_state = 0;

        int start_pos = this.pos;
        int start_line = this.line;

        int accept_state = -1;
        int accept_token = -1;
        int accept_length = -1;
        int accept_pos = -1;
        int accept_line = -1;

        @SuppressWarnings("hiding") int[][][] gotoTable = Lexer.gotoTable[this.state.id()];
        @SuppressWarnings("hiding") int[] accept = Lexer.accept[this.state.id()];
        this.text.setLength(0);

        while(true)
        {
            int c = getChar();

            if(c != -1)
            {
                switch(c)
                {
                case 10:
                    if(this.cr)
                    {
                        this.cr = false;
                    }
                    else
                    {
                        this.line++;
                        this.pos = 0;
                    }
                    break;
                case 13:
                    this.line++;
                    this.pos = 0;
                    this.cr = true;
                    break;
                default:
                    this.pos++;
                    this.cr = false;
                    break;
                }

                this.text.append((char) c);

                do
                {
                    int oldState = (dfa_state < -1) ? (-2 -dfa_state) : dfa_state;

                    dfa_state = -1;

                    int[][] tmp1 =  gotoTable[oldState];
                    int low = 0;
                    int high = tmp1.length - 1;

                    while(low <= high)
                    {
                        // int middle = (low + high) / 2;
                        int middle = (low + high) >>> 1;
                        int[] tmp2 = tmp1[middle];

                        if(c < tmp2[0])
                        {
                            high = middle - 1;
                        }
                        else if(c > tmp2[1])
                        {
                            low = middle + 1;
                        }
                        else
                        {
                            dfa_state = tmp2[2];
                            break;
                        }
                    }
                }while(dfa_state < -1);
            }
            else
            {
                dfa_state = -1;
            }

            if(dfa_state >= 0)
            {
                if(accept[dfa_state] != -1)
                {
                    accept_state = dfa_state;
                    accept_token = accept[dfa_state];
                    accept_length = this.text.length();
                    accept_pos = this.pos;
                    accept_line = this.line;
                }
            }
            else
            {
                if(accept_state != -1)
                {
                    switch(accept_token)
                    {
                    case 0:
                        {
                            @SuppressWarnings("hiding") Token token = new0(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 1:
                        {
                            @SuppressWarnings("hiding") Token token = new1(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 2:
                        {
                            @SuppressWarnings("hiding") Token token = new2(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 3:
                        {
                            @SuppressWarnings("hiding") Token token = new3(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 4:
                        {
                            @SuppressWarnings("hiding") Token token = new4(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 5:
                        {
                            @SuppressWarnings("hiding") Token token = new5(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 6:
                        {
                            @SuppressWarnings("hiding") Token token = new6(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 7:
                        {
                            @SuppressWarnings("hiding") Token token = new7(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 8:
                        {
                            @SuppressWarnings("hiding") Token token = new8(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 9:
                        {
                            @SuppressWarnings("hiding") Token token = new9(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 10:
                        {
                            @SuppressWarnings("hiding") Token token = new10(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 11:
                        {
                            @SuppressWarnings("hiding") Token token = new11(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 12:
                        {
                            @SuppressWarnings("hiding") Token token = new12(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 13:
                        {
                            @SuppressWarnings("hiding") Token token = new13(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 14:
                        {
                            @SuppressWarnings("hiding") Token token = new14(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 15:
                        {
                            @SuppressWarnings("hiding") Token token = new15(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 16:
                        {
                            @SuppressWarnings("hiding") Token token = new16(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 17:
                        {
                            @SuppressWarnings("hiding") Token token = new17(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 18:
                        {
                            @SuppressWarnings("hiding") Token token = new18(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 19:
                        {
                            @SuppressWarnings("hiding") Token token = new19(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 20:
                        {
                            @SuppressWarnings("hiding") Token token = new20(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 21:
                        {
                            @SuppressWarnings("hiding") Token token = new21(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 22:
                        {
                            @SuppressWarnings("hiding") Token token = new22(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 23:
                        {
                            @SuppressWarnings("hiding") Token token = new23(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 24:
                        {
                            @SuppressWarnings("hiding") Token token = new24(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 25:
                        {
                            @SuppressWarnings("hiding") Token token = new25(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 26:
                        {
                            @SuppressWarnings("hiding") Token token = new26(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    }
                }
                else
                {
                    if(this.text.length() > 0)
                    {
                        throw new LexerException(
                            new InvalidToken(this.text.substring(0, 1), start_line + 1, start_pos + 1),
                            "[" + (start_line + 1) + "," + (start_pos + 1) + "]" +
                            " Unknown token: " + this.text);
                    }

                    @SuppressWarnings("hiding") EOF token = new EOF(
                        start_line + 1,
                        start_pos + 1);
                    return token;
                }
            }
        }
    }

    Token new0(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TRouter(text, line, pos); }
    Token new1(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TGroup(text, line, pos); }
    Token new2(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TSegment(text, line, pos); }
    Token new3(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TSettings(text, line, pos); }
    Token new4(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TSetting(text, line, pos); }
    Token new5(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TConnection(text, line, pos); }
    Token new6(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TIpKeyword(text, line, pos); }
    Token new7(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TMain(text, line, pos); }
    Token new8(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TDot(line, pos); }
    Token new9(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TInterfaceType(text, line, pos); }
    Token new10(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TProtocol(text, line, pos); }
    Token new11(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TConst(text, line, pos); }
    Token new12(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TEqual(line, pos); }
    Token new13(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TLParenthesis(line, pos); }
    Token new14(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TRParenthesis(line, pos); }
    Token new15(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TLBrace(line, pos); }
    Token new16(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TRBrace(line, pos); }
    Token new17(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TLBracket(line, pos); }
    Token new18(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TRBracket(line, pos); }
    Token new19(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TArrow(line, pos); }
    Token new20(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TSlash(line, pos); }
    Token new21(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TSemi(text, line, pos); }
    Token new22(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TComma(text, line, pos); }
    Token new23(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TBlank(text, line, pos); }
    Token new24(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TString(text, line, pos); }
    Token new25(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TComment(text, line, pos); }
    Token new26(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TIdentifier(text, line, pos); }

    private int getChar() throws IOException
    {
        if(this.eof)
        {
            return -1;
        }

        int result = this.in.read();

        if(result == -1)
        {
            this.eof = true;
        }

        return result;
    }

    private void pushBack(int acceptLength) throws IOException
    {
        int length = this.text.length();
        for(int i = length - 1; i >= acceptLength; i--)
        {
            this.eof = false;

            this.in.unread(this.text.charAt(i));
        }
    }

    protected void unread(@SuppressWarnings("hiding") Token token) throws IOException
    {
        @SuppressWarnings("hiding") String text = token.getText();
        int length = text.length();

        for(int i = length - 1; i >= 0; i--)
        {
            this.eof = false;

            this.in.unread(text.charAt(i));
        }

        this.pos = token.getPos() - 1;
        this.line = token.getLine() - 1;
    }

    private String getText(int acceptLength)
    {
        StringBuffer s = new StringBuffer(acceptLength);
        for(int i = 0; i < acceptLength; i++)
        {
            s.append(this.text.charAt(i));
        }

        return s.toString();
    }

    private static int[][][][] gotoTable;
/*  {
        { // INITIAL
            {{9, 9, 1}, {10, 10, 2}, {12, 12, 3}, {13, 13, 4}, {32, 32, 5}, {34, 34, 6}, {40, 40, 7}, {41, 41, 8}, {44, 44, 9}, {45, 45, 10}, {46, 46, 11}, {47, 47, 12}, {48, 57, 13}, {59, 59, 14}, {61, 61, 15}, {65, 66, 16}, {67, 67, 17}, {68, 68, 16}, {69, 69, 18}, {70, 70, 19}, {71, 71, 20}, {72, 72, 16}, {73, 73, 21}, {74, 76, 16}, {77, 77, 22}, {78, 78, 16}, {79, 79, 23}, {80, 81, 16}, {82, 82, 24}, {83, 83, 25}, {84, 90, 16}, {91, 91, 26}, {93, 93, 27}, {95, 95, 28}, {97, 98, 29}, {99, 99, 30}, {100, 100, 29}, {101, 101, 31}, {102, 102, 32}, {103, 103, 33}, {104, 104, 29}, {105, 105, 34}, {106, 108, 29}, {109, 109, 35}, {110, 110, 29}, {111, 111, 36}, {112, 113, 29}, {114, 114, 37}, {115, 115, 38}, {116, 122, 29}, {123, 123, 39}, {125, 125, 40}, },
            {{9, 32, -2}, },
            {{9, 32, -2}, },
            {{9, 32, -2}, },
            {{9, 9, 1}, {10, 10, 41}, {12, 32, -2}, },
            {{9, 32, -2}, },
            {{34, 34, 42}, {45, 45, 43}, {48, 57, 44}, {65, 90, 45}, {95, 95, 46}, {97, 122, 47}, },
            {},
            {},
            {},
            {{45, 45, 48}, {48, 57, 49}, {62, 62, 50}, {65, 90, 51}, {95, 95, 52}, {97, 122, 53}, },
            {},
            {{42, 42, 54}, },
            {{48, 57, 13}, },
            {},
            {},
            {{45, 57, -12}, {65, 122, -12}, },
            {{45, 57, -12}, {65, 78, 51}, {79, 79, 55}, {80, 90, 51}, {95, 95, 52}, {97, 110, 53}, {111, 111, 56}, {112, 122, 53}, },
            {{45, 122, -18}, },
            {{45, 57, -12}, {65, 68, 51}, {69, 69, 57}, {70, 90, 51}, {95, 95, 52}, {97, 100, 53}, {101, 101, 58}, {102, 122, 53}, },
            {{45, 57, -12}, {65, 65, 51}, {66, 66, 59}, {67, 81, 51}, {82, 82, 60}, {83, 90, 51}, {95, 95, 52}, {97, 97, 53}, {98, 98, 61}, {99, 113, 53}, {114, 114, 62}, {115, 122, 53}, },
            {{45, 57, -12}, {65, 79, 51}, {80, 80, 63}, {81, 82, 51}, {83, 83, 64}, {84, 90, 51}, {95, 95, 52}, {97, 111, 53}, {112, 112, 65}, {113, 114, 53}, {115, 115, 66}, {116, 122, 53}, },
            {{45, 57, -12}, {65, 65, 67}, {66, 90, 51}, {95, 95, 52}, {97, 97, 68}, {98, 122, 53}, },
            {{45, 57, -12}, {65, 82, 51}, {83, 83, 69}, {84, 95, -23}, {97, 114, 53}, {115, 115, 70}, {116, 122, 53}, },
            {{45, 78, -19}, {79, 79, 71}, {80, 110, -19}, {111, 111, 72}, {112, 122, 53}, },
            {{45, 68, -21}, {69, 69, 73}, {70, 100, -21}, {101, 101, 74}, {102, 122, 53}, },
            {},
            {},
            {{45, 122, -18}, },
            {{45, 122, -18}, },
            {{45, 122, -19}, },
            {{45, 122, -18}, },
            {{45, 122, -21}, },
            {{45, 122, -22}, },
            {{45, 122, -23}, },
            {{45, 122, -24}, },
            {{45, 122, -25}, },
            {{45, 122, -26}, },
            {{45, 122, -27}, },
            {},
            {},
            {{9, 32, -2}, },
            {},
            {{34, 122, -8}, },
            {{34, 122, -8}, },
            {{34, 122, -8}, },
            {{34, 122, -8}, },
            {{34, 122, -8}, },
            {{45, 122, -18}, },
            {{45, 122, -18}, },
            {},
            {{45, 122, -18}, },
            {{45, 122, -18}, },
            {{45, 122, -18}, },
            {{0, 41, 75}, {42, 42, 76}, {43, 65535, 75}, },
            {{45, 57, -12}, {65, 77, 51}, {78, 78, 77}, {79, 90, 51}, {95, 95, 52}, {97, 109, 53}, {110, 110, 78}, {111, 122, 53}, },
            {{45, 122, -57}, },
            {{45, 122, -18}, },
            {{45, 122, -18}, },
            {{45, 122, -18}, },
            {{45, 78, -19}, {79, 79, 79}, {80, 110, -19}, {111, 111, 80}, {112, 122, 53}, },
            {{45, 122, -18}, },
            {{45, 122, -62}, },
            {{45, 122, -18}, },
            {{45, 57, -12}, {65, 72, 51}, {73, 73, 81}, {74, 90, 51}, {95, 95, 52}, {97, 104, 53}, {105, 105, 82}, {106, 122, 53}, },
            {{45, 122, -18}, },
            {{45, 122, -66}, },
            {{45, 72, -66}, {73, 73, 83}, {74, 104, -66}, {105, 105, 84}, {106, 122, 53}, },
            {{45, 122, -69}, },
            {{45, 79, -23}, {80, 80, 85}, {81, 90, 51}, {95, 111, -23}, {112, 112, 86}, {113, 122, 53}, },
            {{45, 122, -71}, },
            {{45, 57, -12}, {65, 84, 51}, {85, 85, 87}, {86, 90, 51}, {95, 95, 52}, {97, 116, 53}, {117, 117, 88}, {118, 122, 53}, },
            {{45, 122, -73}, },
            {{45, 57, -12}, {65, 70, 51}, {71, 71, 89}, {72, 83, 51}, {84, 84, 90}, {85, 90, 51}, {95, 95, 52}, {97, 102, 53}, {103, 103, 91}, {104, 115, 53}, {116, 116, 92}, {117, 122, 53}, },
            {{45, 122, -75}, },
            {{0, 65535, -56}, },
            {{0, 42, -56}, {43, 46, 75}, {47, 47, 93}, {48, 65535, 75}, },
            {{45, 77, -57}, {78, 78, 94}, {79, 109, -57}, {110, 110, 95}, {111, 122, 53}, },
            {{45, 122, -79}, },
            {{45, 84, -73}, {85, 85, 96}, {86, 116, -73}, {117, 117, 97}, {118, 122, 53}, },
            {{45, 122, -81}, },
            {{45, 82, -25}, {83, 83, 98}, {84, 114, -25}, {115, 115, 99}, {116, 122, 53}, },
            {{45, 122, -83}, },
            {{45, 77, -57}, {78, 78, 100}, {79, 109, -57}, {110, 110, 101}, {111, 122, 53}, },
            {{45, 122, -85}, },
            {{45, 57, -12}, {65, 69, 51}, {70, 70, 102}, {71, 90, 51}, {95, 95, 52}, {97, 101, 53}, {102, 102, 103}, {103, 122, 53}, },
            {{45, 122, -87}, },
            {{45, 57, -12}, {65, 83, 51}, {84, 84, 104}, {85, 95, -75}, {97, 115, 53}, {116, 116, 105}, {117, 122, 53}, },
            {{45, 122, -89}, },
            {{45, 57, -12}, {65, 76, 51}, {77, 77, 106}, {78, 90, 51}, {95, 95, 52}, {97, 108, 53}, {109, 109, 107}, {110, 122, 53}, },
            {{45, 83, -89}, {84, 84, 108}, {85, 115, -89}, {116, 116, 109}, {117, 122, 53}, },
            {{45, 122, -91}, },
            {{45, 122, -92}, },
            {{0, 65535, -56}, },
            {{45, 68, -21}, {69, 69, 110}, {70, 100, -21}, {101, 101, 111}, {102, 122, 53}, },
            {{45, 122, -96}, },
            {{45, 79, -23}, {80, 80, 112}, {81, 111, -71}, {112, 112, 113}, {113, 122, 53}, },
            {{45, 122, -98}, },
            {{45, 122, -18}, },
            {{45, 122, -18}, },
            {{45, 122, -18}, },
            {{45, 122, -18}, },
            {{45, 122, -18}, },
            {{45, 122, -18}, },
            {{45, 68, -21}, {69, 69, 114}, {70, 100, -21}, {101, 101, 115}, {102, 122, 53}, },
            {{45, 122, -106}, },
            {{45, 68, -21}, {69, 69, 116}, {70, 100, -21}, {101, 101, 117}, {102, 122, 53}, },
            {{45, 122, -108}, },
            {{45, 72, -66}, {73, 73, 118}, {74, 104, -66}, {105, 105, 119}, {106, 122, 53}, },
            {{45, 122, -110}, },
            {{45, 57, -12}, {65, 66, 51}, {67, 67, 120}, {68, 90, 51}, {95, 95, 52}, {97, 98, 53}, {99, 99, 121}, {100, 122, 53}, },
            {{45, 122, -112}, },
            {{45, 122, -18}, },
            {{45, 122, -18}, },
            {{45, 57, -12}, {65, 81, 51}, {82, 82, 122}, {83, 95, -22}, {97, 113, 53}, {114, 114, 123}, {115, 122, 53}, },
            {{45, 122, -116}, },
            {{45, 77, -57}, {78, 78, 124}, {79, 109, -57}, {110, 110, 125}, {111, 122, 53}, },
            {{45, 122, -118}, },
            {{45, 77, -57}, {78, 78, 126}, {79, 109, -57}, {110, 110, 127}, {111, 122, 53}, },
            {{45, 122, -120}, },
            {{45, 83, -89}, {84, 84, 128}, {85, 115, -89}, {116, 116, 129}, {117, 122, 53}, },
            {{45, 122, -122}, },
            {{45, 122, -18}, },
            {{45, 122, -18}, },
            {{45, 83, -89}, {84, 84, 130}, {85, 115, -89}, {116, 116, 131}, {117, 122, 53}, },
            {{45, 122, -126}, },
            {{45, 70, -75}, {71, 71, 132}, {72, 90, 51}, {95, 102, -75}, {103, 103, 133}, {104, 122, 53}, },
            {{45, 122, -128}, },
            {{45, 72, -66}, {73, 73, 134}, {74, 104, -66}, {105, 105, 135}, {106, 122, 53}, },
            {{45, 122, -130}, },
            {{45, 122, -18}, },
            {{45, 122, -18}, },
            {{45, 82, -25}, {83, 83, 136}, {84, 114, -25}, {115, 115, 137}, {116, 122, 53}, },
            {{45, 122, -134}, },
            {{45, 78, -19}, {79, 79, 138}, {80, 110, -19}, {111, 111, 139}, {112, 122, 53}, },
            {{45, 122, -136}, },
            {{45, 122, -18}, },
            {{45, 122, -18}, },
            {{45, 77, -57}, {78, 78, 140}, {79, 109, -57}, {110, 110, 141}, {111, 122, 53}, },
            {{45, 122, -140}, },
            {{45, 122, -18}, },
            {{45, 122, -18}, },
        }
    };*/

    private static int[][] accept;
/*  {
        // INITIAL
        {23, 23, 23, 23, 23, 23, -1, 13, 14, 22, 26, 8, 20, 11, 21, 12, 26, 26, 9, 9, 9, 26, 26, 26, 26, 26, 17, 18, 26, 26, 26, 9, 9, 9, 26, 26, 26, 26, 26, 15, 16, 23, 24, -1, -1, -1, -1, -1, 26, 26, 19, 26, 26, 26, -1, 26, 26, 9, 9, 9, 26, 9, 26, 6, 26, 6, 26, 26, 26, 26, 26, 26, 26, 26, 26, -1, -1, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 25, 26, 26, 26, 26, 10, 10, 7, 7, 10, 10, 26, 26, 26, 26, 26, 26, 26, 26, 1, 1, 26, 26, 26, 26, 26, 26, 26, 26, 0, 0, 26, 26, 26, 26, 26, 26, 2, 2, 4, 4, 26, 26, 3, 3, 26, 26, 5, 5, },

    };*/

    public static class State
    {
        public final static State INITIAL = new State(0);

        private int id;

        private State(@SuppressWarnings("hiding") int id)
        {
            this.id = id;
        }

        public int id()
        {
            return this.id;
        }
    }

    static 
    {
        try
        {
            DataInputStream s = new DataInputStream(
                new BufferedInputStream(
                Lexer.class.getResourceAsStream("lexer.dat")));

            // read gotoTable
            int length = s.readInt();
            gotoTable = new int[length][][][];
            for(int i = 0; i < gotoTable.length; i++)
            {
                length = s.readInt();
                gotoTable[i] = new int[length][][];
                for(int j = 0; j < gotoTable[i].length; j++)
                {
                    length = s.readInt();
                    gotoTable[i][j] = new int[length][3];
                    for(int k = 0; k < gotoTable[i][j].length; k++)
                    {
                        for(int l = 0; l < 3; l++)
                        {
                            gotoTable[i][j][k][l] = s.readInt();
                        }
                    }
                }
            }

            // read accept
            length = s.readInt();
            accept = new int[length][];
            for(int i = 0; i < accept.length; i++)
            {
                length = s.readInt();
                accept[i] = new int[length];
                for(int j = 0; j < accept[i].length; j++)
                {
                    accept[i][j] = s.readInt();
                }
            }

            s.close();
        }
        catch(Exception e)
        {
            throw new RuntimeException("The file \"lexer.dat\" is either missing or corrupted.");
        }
    }
}
